export const db=[
    {
        id: 91,
        name: "ประสาน ศรีโสภา",
        date: "2020-12-13",
        hn: 'HN00001',
        sex: "Male",
        time: "12.30",

        originHospital: "Hostpital A",
        destinationHospital: "Hostpital B",
        createBy:"นายแพทย์ A",
        status: "รอการยืนยัน",
        urgent:"Emergency",


        nationality: "ไทย",
        tel: '0123456789',
        group: 'VVIP',
        location: "A -> B",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
        department: "A",
        informant: "9",
        point: 3
    },
    {
        id: 92,
        name: "Zoey Lang",
        hn: 'HN00002',
        date: "2020-11-13",
        sex: "Female",
        time: "11.30",
        status: "active",

        originHospital: "Hostpital A",
        destinationHospital: "Hostpital B",
        createBy:"นายแพทย์ A",
        status: "รอการยืนยัน",
        urgent:"Emergency",

        tel: '0123456789',
        group: 'VVIP',
        nationality: "ไทย",
        location: "C -> B",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
        department: "B",
        informant: "A",
        point: 309
    },
    {
        id: 93,
        name: "Jane Fisher",
        hn: 'HN00003',
        date: "2020-12-19",
        sex: "Female",
        time: "04.30",
        tel: '0123456789',
        group: 'ทั่วไป',
        status: "active",
       

        originHospital: "Hostpital A",
        destinationHospital: "Hostpital B",
        createBy:"นายแพทย์ A",
        status: "รอการยืนยัน",
        urgent:"Urgency",

        nationality: "ไทย",
        location: "A -> C",
        avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
        department: "C",
        informant: "S",
        point: 388
    },
    {
        id: 93,
        name: "Jane Fisher",
        hn: 'HN00003',
        date: "2020-12-19",
        sex: "Female",
        time: "04.30",
        tel: '0123456789',
        group: 'ทั่วไป',
        status: "active",

        originHospital: "Hostpital A",
        destinationHospital: "Hostpital B",
        createBy:"นายแพทย์ A",
        status: "รอการยืนยัน",
        urgent:"Urgency",

        nationality: "ไทย",
        location: "A -> C",
        avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
        department: "C",
        informant: "S",
        point: 388
    },
    {
        id: 93,
        name: "Jane Fisher",
        hn: 'HN00003',
        date: "2020-12-19",
        sex: "Female",
        time: "04.30",
        tel: '0123456789',
        group: 'ทั่วไป',
        status: "active",
        urgent:"Urgency",

        originHospital: "Hostpital A",
        destinationHospital: "Hostpital B",
        createBy:"นายแพทย์ A",
        status: "รอการยืนยัน",

        nationality: "ไทย",
        location: "A -> C",
        avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
        department: "C",
        informant: "S",
        point: 388
    },
    {
        id: 93,
        name: "Jane Fisher",
        hn: 'HN00003',
        date: "2020-12-19",
        sex: "Female",
        time: "04.30",
        tel: '0123456789',
        group: 'ทั่วไป',
        status: "active",
        urgent:"Urgency",

        originHospital: "Hostpital A",
        destinationHospital: "Hostpital B",
        createBy:"นายแพทย์ A",
        status: "รอการยืนยัน",

        nationality: "ไทย",
        location: "A -> C",
        avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
        department: "C",
        informant: "S",
        point: 388
    },
    {
        id: 94,
        name: "William Howard",
        date: "2020-02-13",
        hn: 'HN00004',
        time: "04.30",
        sex: "Male",
        nationality: "ไม่ระบุ",
        tel: '0123456789',
        group: 'ทั่วไป',
        status: "active",
        urgent:"Elective",

        originHospital: "Hostpital A",
        destinationHospital: "Hostpital B",
        createBy:"นายแพทย์ A",
        status: "รอการยืนยัน",

        location: "A -> B",
        avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
        department: "D",
        informant: "W",
        point: 0
    },
    {
        id: 95,
        name: "Kristen Copper",
        date: "2020-12-13",
        hn: 'HN00005',
        time: "02.30",
        sex: "Female",
        nationality: "ไทย",
        tel: '0123456789',
        group: 'ทั่วไป',
        status: "active",

        originHospital: "Hostpital A",
        destinationHospital: "Hostpital B",
        createBy:"นายแพทย์ A",
        status: "รอการยืนยัน",
        urgent:"Elective",

        location: "A -> F",
        avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
        department: "E",
        informant: "8",
        point: 989
    },
    {
        id: 96,
        name: "Kristen Copper",
        date: "2020-12-13",
        hn: 'HN00006',
        time: "12.00",
        sex: "Female",
        nationality: "ไทย",
        tel: '',
        group: 'ทั่วไป',
        status: "active",

        originHospital: "Hostpital A",
        destinationHospital: "Hostpital B",
        createBy:"นายแพทย์ A",
        status: "รอการยืนยัน",
        urgent:"Elective",

        location: "A -> B",
        avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
        department: "A",
        informant: "y",
        point: 564
    },
    {
        id: 97,
        name: "Kristen Copper",
        date: "2020-12-13",
        time: "12.40",
        sex: "Female",
        nationality: "ไม่ระบุ",
        tel: '',
        group: 'ทั่วไป',
        hn: 'HN00007',
        status: "inactive",
        

        originHospital: "Hostpital A",
        destinationHospital: "Hostpital B",
        createBy:"นายแพทย์ A",
        status: "รอการยืนยัน",
        urgent:"Elective",

        location: "B -> C",
        avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
        department: "B",
        informant: "g",
        point: 376
    },
    {
        id: 98,
        name: "Kristen Copper",
        date: "2020-05-13",
        time: "12.30",
        sex: "Female",
        nationality: "ไทย",
        tel: '',
        group: 'ทั่วไป',
        hn: 'HN00008',
        status: "inactive",

        originHospital: "Hostpital A",
        destinationHospital: "Hostpital B",
        createBy:"นายแพทย์ A",
        status: "รอการยืนยัน",
        urgent:"Elective",
        
        location: "B -> A",
        avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
        department: "C",
        informant: "00",
        point: 354
    },
    {
        id: 99,
        name: "Kristen Copper",
        date: "2020-05-13",
        time: "12.40",
        hn: 'HN00009',
        sex: "Female",
        status: "cancel",
        nationality: "ไทย",
        tel: '0123456789',
        group: 'ทั่วไป',
        location: "B -> C",
        avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
        department: "B",
        informant: "g",
        point: 99
    },
    {
        id: 100,
        name: "Kristen Copper",
        date: "2020-05-13",
        time: "12.30",
        sex: "Female",
        nationality: "ไทย",
        tel: '0123456789',
        group: 'ทั่วไป',
        hn: 'HN00010',
        status: "cancel",
        location: "B -> A",
        avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
        department: "C",
        informant: "00",
        point: 83
    },
];